// Type definitions for JtsDev 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace JtsDev {
  export interface MemberDefaultMappingTest {
    member_Boolean: boolean;
    member_Integer: number;
    member_Object: Object;
    member_boolean: boolean;
    member_char: string;
    member_double: number;
    member_float: number;
    member_int: number;
    member_long: number;
    member_o_Long: number;
    member_o_character: string;
    member_o_double: number;
    member_o_float: number;
    member_o_short: number;
    member_short: number;
  }

 }
