// Type definitions for MyModule 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace MyModule {
  /**
   *  Sample documentation of an enum
   */
  export enum DocumentEnum {
    /**
     *  DOC_A documentation
     */
    DOC_A,
    DOC_B
  }

  /**
   *  Sample documentation for a class
   */
  export interface DocumentationTests {
    docEnum: DocumentEnum;
    /**
     *  multi line
     *  comments
     *  @return some value
     */
    docInt: number;
  }

 }
