// Type definitions for MyModule 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace MyModule {
    /**
     *  Sample documentation for a class
     */
    export interface DocumentationTests {
        docInt: number;
    }

 }
