// Type definitions for inherit1_test 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace inherit1_test {
  export interface Inherit1SecondChild extends Inherit1FirstClass {
    aNumber: number;
    readonly fromTheParent: string;
    readonly inherit1FirstClass: string;
    someFinalString: string;
  }

  export interface TheParentType {
    readonly fromTheParent: string;
  }

  export interface Inherit1FirstClass extends TheParentType {
    readonly inherit1FirstClass: string;
  }

 }
