// Type definitions for MyModule 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace MyModule {
  export interface InterFaceTest {
    readonly someInt: number;
    readonly someString: string;
  }

 }
