// Type definitions for MyModule 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace MyModule {
  export namespace jts {
    export namespace dev {
      export interface InterFaceTest {
        readonly someString: string;
        readonly someInt: number;
      }
    }
  }
 }
